version: '2'

services:
  nginx:
    build: docker/nginx
    ports:
      - 8080:80
    volumes_from:
      - app
  app:
    command: "true"
    image: alpine:3.4
    volumes:
      - .:/var/www/app
    environment:
      PHP_EXTENSION_XDEBUG: 1
  php:
    build: docker/php
    expose:
      - 9000
    volumes:
      - composer-cache:/composer/cache
    volumes_from:
      - app

  mysql:
    image: mysql:5.7
    volumes:
      - .:/code
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=slim_app_db
      - MYSQL_USER=slim_user
      - MYSQL_PASSWORD=password
    ports:
      - "8082:3306"

volumes:
  composer-cache:
    driver: local
